<a href="https://colab.research.google.com/github/milanfx/Expressway-to-DTSA/blob/main/4.%20Data%20Wrangling%20with%20Python/1.%20Data%20Wrangling%20Fundamental/W3_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table width="850">
<td bgcolor="#ba2f2a"><font color="white" size="8"><b>
W3 Python Numpy
</b></font></td></table>

<table width="850">
<td bgcolor="#d5695d"><font color="white" size="6"><b>
1. Numpy Basics
</b></font></td></table>


<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.1 Creation
</b><br><br>
Task:
</font></td></table>

In [ ]:
import numpy as np

In [ ]:
# list to array
ls = [1,2,3,4,5]
np.array(ls)

array([1, 2, 3, 4, 5])

In [ ]:
ar1 = np.arange(10)
print('ar1:', ar1)

ar2 = np.arange(5,11)
print('ar2:', ar2)

ar3 = np.arange(0,13,3)
print('ar3:', ar3)

ar4 = np.arange(4,-4,-1)
print('ar4:', ar4)

ar1: [0 1 2 3 4 5 6 7 8 9]
ar2: [ 5  6  7  8  9 10]
ar3: [ 0  3  6  9 12]
ar4: [ 4  3  2  1  0 -1 -2 -3]


In [ ]:
ar5 = np.arange(1,5,1)
print(ar5, type(ar5[0]))

ar6 = np.arange(1,5,.5)
print(ar6, type(ar6[0]))

ar7 = np.arange(1,5, dtype=float)
print(ar7, type(ar7[0]))

[1 2 3 4] <class 'numpy.int64'>
[1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.float64'>
[1. 2. 3. 4.] <class 'numpy.float64'>


In [ ]:
ar = np.array([1,2,3,4,5])
ar_type = type(ar)
array_size = np.size(ar)
array_dimensions = ar.ndim
array_data_type = ar.dtype

print('''Object type: {}
Array size: {},
Array dimensions: {},
Array data type: {}'''.format(ar_type,
                              array_size,
                              array_dimensions,
                              array_data_type))

Object type: <class 'numpy.ndarray'>
Array size: 5,
Array dimensions: 1,
Array data type: int64


<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.2 Ndarray and List
</b><br><br>
Task:
</font></td></table>

In [ ]:
ls = [x**2 for x in range(10)]
ar = np.arange(10) ** 2
print(ls)
print(ar)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
print(ls[:3])
print(ar[:3])

[0, 1, 4]
[0 1 4]


In [ ]:
ls = [1,2,3,4,5]
print(ls)
print(ls + ls)
print(ls * 2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
ar = np.arange(1,6)
print(ar)
print(ar + ar)
print(ar * 2)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [ ]:
s = 2
ls = [2,2,2,2,2]
ar2 = np.array( [2,2,2,2,2] )

print(ar * s)
print(ar * ls)
print(ar * ar2)

print(ar + s)
print(ar - s)
print(ar / s)
print(ar ** s)
print(ar ** .5)
print(ar % s)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[3 4 5 6 7]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1 0 1 0 1]


<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.3 Ndarray and List
</b><br><br>
Task:
</font></td></table>

In [ ]:
ar1 = np.arange(1,10)
ar2 = np.arange(10,1,-1)
ar1, ar2, np.multiply(ar1,ar2)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10,  9,  8,  7,  6,  5,  4,  3,  2]),
 array([10, 18, 24, 28, 30, 30, 28, 24, 18]))

In [ ]:
ar1.dot(ar2)

210

In [ ]:
ar1@ar2

210

### Some Examples of Universal Functions

In [ ]:
ar_ints = np.arange(1,6)
ar_floats = np.arange(1,7.5,1.5)

In [ ]:
np.add(ar_ints, ar_floats)

array([ 2. ,  4.5,  7. ,  9.5, 12. ])

In [ ]:
np.negative(ar_ints)

array([-1, -2, -3, -4, -5])

In [ ]:
np.square(ar_ints)

array([ 1,  4,  9, 16, 25])

In [ ]:
np.hypot(ar_ints, ar_ints)

array([1.41421356, 2.82842712, 4.24264069, 5.65685425, 7.07106781])

In [ ]:
np.greater(ar_ints, ar_floats)

array([False, False, False, False, False])

In [ ]:
np.ceil(ar_floats)

array([1., 3., 4., 6., 7.])

<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.4 Statistics
</b><br><br>
Task:
</font></td></table>

In [ ]:
ar3 = np.random.randint(0, 10, (10))
ar3

array([5, 2, 4, 8, 3, 1, 6, 9, 3, 8])

In [ ]:
ar3.sum(),ar3.mean(), ar3.std(), ar3.var(), ar3.max(), ar3.min()

(49, 4.9, 2.6248809496813377, 6.890000000000001, 9, 1)

<table width="850">
<td bgcolor="#d5695d"><font color="white" size="6"><b>
2. Multi-dimensional Arrays
</b></font></td></table>


<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
2.1 Creation and Access
</b><br><br>
Task:
</font></td></table>

In [ ]:
mda = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

print('Num dimensions: ', mda.ndim)
print('Second row: ', mda[1, :])
print('Second column: ', mda[:, 1]) #short hand
print('2nd element in 2nd row:', mda[1, 1])

Num dimensions:  2
Second row:  [4 5 6]
Second column:  [2 5 8]
2nd element in 2nd row: 5


In [ ]:
mda.size

9

In [ ]:
mda.shape

(3, 3)

In [ ]:
# Cell
row3cell2 = mda[2,1]
row3cell2

8

In [ ]:
# Row
row2 = mda[1,:]
row2, type(row2), row2.ndim

(array([4, 5, 6]), numpy.ndarray, 1)

In [ ]:
# Column
col2 = mda[:,1]
col2, type(col2), col2.ndim

(array([2, 5, 8]), numpy.ndarray, 1)

In [ ]:
cols2and3 = mda[:,1:3]
cols2and3

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
cols2and3 = mda[:,-2:]
cols2and3

array([[2, 3],
       [5, 6],
       [8, 9]])

<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
2.2 Manipulation
</b><br><br>
Task:
</font></td></table>

In [ ]:
# Add value
print(mda)
print('-' * 20)
mda[-2:, -2:] += 2
print(mda)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[ 1  2  3]
 [ 4  7  8]
 [ 7 10 11]]


In [ ]:
# Add Vector
mda = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
v = [10, 20, 30]
print(mda + v)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
ar1 = np.zeros(shape=(6,3), dtype=float)
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar2 = ar1.reshape(2,-1)
ar2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
ar3 = ar2.reshape(-1,2)
ar3

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ar4 = np.linspace(4, 6, 5)
ar4

array([4. , 4.5, 5. , 5.5, 6. ])

In [ ]:
ar5 = np.arange(1, 7).reshape(2, 3)
ar6 = np.arange(7, 13).reshape(2, 3)
ar5, ar6

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [ ]:
ar5 + ar6

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
ar5 * ar6

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
ar5.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
ar5.T@ar6

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [ ]:
ar5.T.dot(ar6)

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [ ]:
ar6@ar5.T

array([[ 50, 122],
       [ 68, 167]])

<table width="850">
<td bgcolor="#d5695d"><font color="white" size="6"><b>
3. Numpy Mask ---- Boolean Arrays
</b></font></td></table>


<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
3.1 Boolean Arrays
</b><br><br>
Task:
</font></td></table>

In [ ]:
np.random.seed(1)
ar = np.random.randint(100, size=10)
ar

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [ ]:
# Odd
ar[ar % 2 == 1]

array([71, 25, 11, 29, 87, 87, 13,  9,  7, 63, 61, 57,  1, 81, 13, 47, 71,
        3, 21, 49, 57,  3, 43, 41, 15, 25, 87,  7, 25,  9, 67, 23, 27, 37,
       57, 83, 23, 15, 87, 25, 71, 23, 55, 65, 77,  3, 77, 85, 91, 21])

In [ ]:
ar = np.random.randint(100, size = (10, 10))
ar

array([[76, 71,  6, 25, 50, 20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87, 87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22, 57,  1,  0, 60, 81],
       [ 8, 88, 13, 47, 72, 30, 71,  3, 70, 21],
       [49, 57,  3, 68, 24, 43, 76, 26, 52, 80],
       [41, 82, 15, 64, 68, 25, 98, 87,  7, 26],
       [25, 22,  9, 67, 23, 27, 37, 57, 83, 38],
       [ 8, 32, 34, 10, 23, 15, 87, 25, 71, 92],
       [74, 62, 46, 32, 88, 23, 55, 65, 77,  3],
       [ 0, 77,  6, 52, 85, 70,  2, 76, 91, 21]])

In [ ]:
# Even
ar[ar % 2 == 0]

array([76,  6, 50, 20, 18, 84, 28, 14, 50, 68, 94, 96, 86, 22,  0, 60,  8,
       88, 72, 30, 70, 68, 24, 76, 26, 52, 80, 82, 64, 68, 98, 26, 22, 38,
        8, 32, 34, 10, 92, 74, 62, 46, 32, 88,  0,  6, 52, 70,  2, 76])

In [ ]:
# <50
ar[ar < 50]

array([ 6, 25, 20, 18, 11, 28, 29, 14, 13,  9,  7, 22,  1,  0,  8, 13, 47,
       30,  3, 21, 49,  3, 24, 43, 26, 41, 15, 25,  7, 26, 25, 22,  9, 23,
       27, 37, 38,  8, 32, 34, 10, 23, 15, 25, 46, 32, 23,  3,  0,  6,  2,
       21])

In [ ]:
ar2 = np.random.randint(100, size = (10, 10))
ar2

array([[46,  0, 29, 63, 75, 35, 53, 93, 33,  2],
       [84, 83, 48, 54, 32, 28, 55, 82, 31, 28],
       [94, 74,  8, 99, 32,  8, 84, 77, 50, 79],
       [41, 64, 83, 24, 20, 44, 15, 30, 91, 14],
       [19, 26, 86,  7, 99, 53, 47, 60, 34, 32],
       [19, 67, 24, 83, 94, 38, 47,  5, 79, 63],
       [87, 32, 42, 74, 66, 88, 98, 30, 17, 68],
       [64, 60, 78, 17, 39, 35, 81, 28, 22, 38],
       [41, 74, 77, 70, 25, 48, 50, 62, 44, 54],
       [ 0, 86, 16, 19,  9, 92, 51, 10, 68, 23]])

In [ ]:
ar[ar < ar2]

array([ 6, 25, 50, 20, 18, 84, 11, 29, 14, 13,  9,  7, 61, 22,  1,  0,  8,
       13, 30,  3, 70,  3, 24, 43, 26, 15, 64, 68, 25,  7, 26, 25, 22,  9,
       67, 23, 27, 37, 38,  8, 32, 34, 10, 23, 15, 25, 62, 46, 32, 23,  3,
       77,  6, 70,  2, 21])

In [ ]:
ar[ar + ar2 > 100]

array([76, 50, 84, 29, 68, 87, 87, 94, 96, 86,  9, 61, 60, 81, 88, 70, 24,
       76, 80, 82, 64, 68, 98, 25, 67, 27, 37, 38, 34, 87, 92, 74, 62, 46,
       32, 88, 55, 65, 77, 77, 70, 91])

<table width="850">
<td bgcolor="#d5695d"><font color="white" size="6"><b>
4. Numpy Lab
</b></font></td></table>


In [ ]:
import numpy as np

In [ ]:
x1 = np.array([1, 2, 3, 4, 5])
x1

array([1, 2, 3, 4, 5])

In [ ]:
x2 = np.zeros(6)
x2

array([0., 0., 0., 0., 0., 0.])

In [ ]:
x3 = np.ones(6)
x3

array([1., 1., 1., 1., 1., 1.])

In [ ]:
x4 = np.arange(11)
x4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x5 = np.zeros((2, 3))
x5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x6 = np.ones((3, 2))
x6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
x7 = np.random.randint(0, 10, (3, 2))
x7

array([[5, 3],
       [8, 8],
       [0, 6]])

In [ ]:
x8 = np.random.random((10, 2))
x8

array([[0.5409518 , 0.95943432],
       [0.80396089, 0.03232307],
       [0.70938725, 0.46500148],
       [0.94754894, 0.22143273],
       [0.26707202, 0.08147396],
       [0.42861883, 0.10901876],
       [0.63378676, 0.80296324],
       [0.6968005 , 0.76621138],
       [0.34245412, 0.84585148],
       [0.42876877, 0.82400987]])