<a href="https://colab.research.google.com/github/milanfx/Expressway-to-DTSA/blob/main/4.%20Data%20Wrangling%20with%20Python/1.%20Data%20Wrangling%20Fundamental/W5_Python_Case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table width="850">
<td bgcolor="#ba2f2a"><font color="white" size="8"><b>
W5 Python Case
</b></font></td></table>

<table width="850">
<td bgcolor="#d5695d"><font color="white" size="6"><b>
1. Panda Case
</b></font></td></table>


<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.1 Data Generation
</b><br><br>
1. ChannelID (Y0001, Y0002, ...) <br>
2. Number of subscribers <br>
3. Number of videos <br>
4. Number of total views <br>
5. Category (['music','news','gaming','food','travel']) <br>
6. Language (['English','Spanish','Japanese','Franch','Russia','Chinese']) <br>
7. Type(['Corperate','Goverment','NGO','Individual'])
</font></td></table>

In [ ]:
import random
import numpy as np
import pandas as pd

In [ ]:
# We make this variable SIZE because it supposed to be constant for the runtime.
SIZE = 10000

In [ ]:
# 1. Generate ChannelID
ids = ['Y{0:04d}'.format(x) for x in range(SIZE)]
ids[:5], ids[-5:]

(['Y0000', 'Y0001', 'Y0002', 'Y0003', 'Y0004'],
 ['Y9995', 'Y9996', 'Y9997', 'Y9998', 'Y9999'])

In [ ]:
# 2. Generate # of subscriber
subs = np.random.normal(100000, 50000, (SIZE))
subs = subs.astype(int)
subs[subs <= 0 ] = 1
subs[:5], subs[-5:]

(array([179125,  99604,  51677,  82102,  75292]),
 array([ 94824, 178004,      1, 119896,  82274]))

In [ ]:
# 3. Generate number of videos
nvideos = [np.random.randint(1, 100) for i in range(SIZE)]
nvideos[:5], nvideos[-5:]

([33, 42, 18, 3, 31], [78, 7, 36, 34, 28])

In [ ]:
# 4. simulate the number of views
views = [ int(x*1.5*np.random.random() + y*2*np.random.random() + np.random.randint(-1000, 1000))
for x, y in zip(subs, nvideos)]
views = np.array(views)
views[views < 0] = 0
views[:5], views[-5:]

(array([83983, 13185, 33816,  6534, 39252]),
 array([135012, 126636,    756,   4882, 109529]))

In [ ]:
# 5. Random Category
category = np.random.choice(['music','news','gaming','food','travel'], SIZE)
category[:5], category[-5:]

(array(['news', 'news', 'food', 'news', 'music'], dtype='<U6'),
 array(['news', 'music', 'news', 'food', 'gaming'], dtype='<U6'))

In [ ]:
# 6. Random Language
language = np.random.choice(['English','Spanish','Japanese','Franch','Russia','Chinese'],
                            SIZE, p=[0.5, 0.1, 0.1, 0.1, 0.1, 0.1])
language[:5], language[-5:]

(array(['English', 'Chinese', 'Franch', 'English', 'Spanish'], dtype='<U8'),
 array(['English', 'Chinese', 'English', 'English', 'Russia'], dtype='<U8'))

In [ ]:
# 7. Random Type
tp = np.random.choice(['Corperate','Goverment','NGO','Individual'], SIZE, p=[0.1, 0.2, 0.3, 0.4])
tp[:5], tp[-5:]

(array(['Individual', 'NGO', 'Individual', 'Individual', 'Individual'],
       dtype='<U10'),
 array(['Goverment', 'NGO', 'NGO', 'Individual', 'Individual'],
       dtype='<U10'))

In [ ]:
#  Combine as a df
df = pd.DataFrame({'ChannelID': ids,
                   'subs': subs,
                   'nvideos': nvideos,
                   'views': views,
                   'Category': category,
                   'Language':language,
                   'Type': tp},
                  index = ids)
df.head()

ChannelID    subs  nvideos  views Category Language        Type
Y0000     Y0000  179125       33  83983     news  English  Individual
Y0001     Y0001   99604       42  13185     news  Chinese         NGO
Y0002     Y0002   51677       18  33816     food   Franch  Individual
Y0003     Y0003   82102        3   6534     news  English  Individual
Y0004     Y0004   75292       31  39252    music  Spanish  Individual

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, Y0000 to Y9999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ChannelID  10000 non-null  object
 1   subs       10000 non-null  int64 
 2   nvideos    10000 non-null  int64 
 3   views      10000 non-null  int64 
 4   Category   10000 non-null  object
 5   Language   10000 non-null  object
 6   Type       10000 non-null  object
dtypes: int64(3), object(4)
memory usage: 625.0+ KB


In [ ]:
df.to_csv('/content/youtube_channels.csv', index=False)

<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.2 Data Selection
</b><br><br>
1. Random Sample <br>
2. Most Popular
</font></td></table>

In [ ]:
# 1. random sample
df_random = df.iloc[random.sample(range(0, SIZE+1), 10)]
df_random

ChannelID    subs  nvideos   views Category  Language        Type
Y5867     Y5867  103594       83   63017     food    Franch   Goverment
Y1291     Y1291  186257       12  264609     news  Japanese   Goverment
Y1542     Y1542   36512       64   52620   travel   Spanish   Corperate
Y3523     Y3523   73099       14   84839     food    Russia   Goverment
Y6024     Y6024       1       77    1032     news    Russia  Individual
Y1963     Y1963  178093       84  198040     news   English  Individual
Y1878     Y1878  105383       79   74293    music   Chinese  Individual
Y0031     Y0031   76844       89   90006    music   English   Goverment
Y5472     Y5472   94404       28  136811   travel   Chinese         NGO
Y7300     Y7300  173993       40   77338   travel    Franch  Individual

In [ ]:
# 2. Most popular
df_superp = df[df['subs'] > 250000]
df_superp

ChannelID    subs  nvideos   views Category  Language        Type
Y0394     Y0394  275067       22  204358   travel    Franch         NGO
Y0963     Y0963  274860       13  125212     news   English         NGO
Y2813     Y2813  262611       91   49780     news   English  Individual
Y4698     Y4698  260403       48  196727     news   Spanish         NGO
Y5261     Y5261  256982       55  181042     news   English  Individual
Y5957     Y5957  266573       62  282160   gaming  Japanese  Individual
Y6105     Y6105  284520       63  232659   travel  Japanese   Goverment
Y6173     Y6173  252697       83  121694   travel   English   Goverment
Y6776     Y6776  301779       48  400118     news    Franch         NGO
Y7111     Y7111  255869       60  148096     news    Russia   Goverment
Y8257     Y8257  277829       87  384320    music    Russia   Corperate
Y8309     Y8309  287413       19  308002   travel   English   Goverment
Y8741     Y8741  261589       71  349442   travel   Spanish         NGO
Y9173     Y9173  271956        3  135042     news   English         NGO

In [ ]:
# Most popular - English
df_EnglishP = df[(df['subs'] > 250000) & (df['Language'] == 'English')]
df_EnglishP

ChannelID    subs  nvideos   views Category Language        Type
Y0963     Y0963  274860       13  125212     news  English         NGO
Y2813     Y2813  262611       91   49780     news  English  Individual
Y5261     Y5261  256982       55  181042     news  English  Individual
Y6173     Y6173  252697       83  121694   travel  English   Goverment
Y8309     Y8309  287413       19  308002   travel  English   Goverment
Y9173     Y9173  271956        3  135042     news  English         NGO

In [ ]:
# Most popular - Game
df_gaming_nv = df[(df['Category'] == 'gaming') & (df['nvideos'] > 98)]
df_gaming_nv

ChannelID    subs  nvideos   views Category  Language        Type
Y0923     Y0923   44573       99   25858   gaming   Chinese         NGO
Y1967     Y1967  133794       99  140453   gaming   Spanish         NGO
Y2328     Y2328  123853       99   58698   gaming   Chinese  Individual
Y2818     Y2818  122599       99   79499   gaming    Russia   Goverment
Y3443     Y3443    5872       99    3943   gaming   English         NGO
Y5922     Y5922  142518       99  100525   gaming   English   Goverment
Y6946     Y6946  109196       99   49096   gaming    Russia         NGO
Y6959     Y6959  134675       99   98669   gaming  Japanese  Individual
Y8157     Y8157   80586       99   12738   gaming   Chinese         NGO
Y8526     Y8526   73128       99   55183   gaming   Spanish  Individual
Y8566     Y8566  188162       99   87244   gaming   English   Corperate
Y9229     Y9229  220452       99   74599   gaming    Russia         NGO

In [ ]:
# Top Subs and Top nvideos
df_subs_and_nvideos = df[(df['subs'] > 200000) & (df['nvideos'] > 95)]
df_subs_and_nvideos

ChannelID    subs  nvideos   views Category  Language        Type
Y2579     Y2579  211318       98   56441   travel   English   Goverment
Y2665     Y2665  240989       98  160129     news    Russia  Individual
Y3393     Y3393  203604       99  292498    music   English  Individual
Y4997     Y4997  204858       96   99446     food   English   Corperate
Y7497     Y7497  210920       97  112412    music    Franch         NGO
Y8641     Y8641  210295       99   98191   travel  Japanese  Individual
Y8647     Y8647  209556       99  245219     food    Russia   Corperate
Y9229     Y9229  220452       99   74599   gaming    Russia         NGO

<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.3 Data Aggregation
</b><br><br>
1. By Category <br>
2. By Language <br>
3. By Language and Type
</font></td></table>

In [ ]:
byCategory = df.groupby('Category')
round(byCategory.mean(),1)

<ipython-input-51-306a5dcf6178>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(byCategory.mean(),1)


subs  nvideos    views
Category                            
food       98661.0     51.4  74955.4
gaming     99463.0     49.7  73896.3
music      99146.0     50.1  75724.2
news      102561.7     50.1  75300.9
travel     99580.0     50.4  76357.9

In [ ]:
byLanguage = df.groupby('Language')
round(byLanguage.mean(),1)

<ipython-input-52-6639d073fb97>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(byLanguage.mean(),1)


subs  nvideos    views
Language                            
Chinese   100492.8     50.7  75198.6
English   100001.9     50.4  75720.3
Franch     99063.6     49.2  74955.4
Japanese  102977.3     49.8  77975.6
Russia     98717.5     51.2  72668.9
Spanish    97572.8     50.5  73086.3

In [ ]:
byLanType = df.groupby(['Language', 'Type'])
round(byLanType.mean(),1)

<ipython-input-53-2043915376f9>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(byLanType.mean(),1)


subs  nvideos    views
Language Type                                  
Chinese  Corperate    94781.6     50.3  70925.5
         Goverment    99196.7     52.9  75736.6
         Individual  103732.2     51.6  76343.9
         NGO          98601.3     48.4  74590.3
English  Corperate   100020.8     50.5  73882.9
         Goverment   103008.8     51.1  76510.9
         Individual   99243.0     49.8  75952.2
         NGO          99028.3     50.7  75485.7
Franch   Corperate   101431.8     46.9  75673.4
         Goverment   100395.8     52.1  68687.4
         Individual   96967.1     47.1  76080.0
         NGO         100202.0     50.8  77482.7
Japanese Corperate   105304.7     51.3  78715.3
         Goverment   106426.6     49.4  79267.0
         Individual  105279.4     49.3  83460.7
         NGO          97106.2     50.1  69926.1
Russia   Corperate   108692.3     52.9  88053.7
         Goverment   108469.1     47.9  75444.3
         Individual   94946.8     51.6  73581.1
         NGO          94763.1     51.9  64983.1
Spanish  Corperate    96169.0     48.5  72353.8
         Goverment    95447.9     48.0  72147.8
         Individual   98530.6     50.3  72445.6
         NGO          98215.3     53.3  74832.8

<table width="850">
<td bgcolor="#f8f2e4"><font color="black" size="4"><b>
1.4 Data Manipulation
</b><br><br>
1. Sub per Video <br>
2. View Per Video <br>
3. View per Sub
</font></td></table>

### Manipulation

In [ ]:
df['subpervideo'] = df['subs']/df['nvideos']
df['subpervideo'].describe()

count     10000.000000
mean       5221.694045
std       13163.607975
min           0.010101
25%        1148.963891
50%        1969.191286
75%        3914.088034
max      221325.000000
Name: subpervideo, dtype: float64

In [ ]:
df['viewspervideo'] = df['views']/df['nvideos']
df['viewspervideo'].describe()

count     10000.000000
mean       3993.900729
std       11925.652355
min           0.000000
25%         526.455079
50%        1313.034345
75%        2916.534420
max      320213.000000
Name: viewspervideo, dtype: float64

In [ ]:
df['viewspersub'] = df['views']/df['subs']
df['viewspersub'].describe()

count    10000.000000
mean         8.333431
std         73.179088
min          0.000000
25%          0.366247
50%          0.751609
75%          1.144531
max       1136.000000
Name: viewspersub, dtype: float64

In [ ]:
df.head(10)

ChannelID    subs  nvideos  views Category Language        Type  \
Y0000     Y0000  179125       33  83983     news  English  Individual   
Y0001     Y0001   99604       42  13185     news  Chinese         NGO   
Y0002     Y0002   51677       18  33816     food   Franch  Individual   
Y0003     Y0003   82102        3   6534     news  English  Individual   
Y0004     Y0004   75292       31  39252    music  Spanish  Individual   
Y0005     Y0005   29587       92  43377   travel  Spanish  Individual   
Y0006     Y0006   81750       43  50811     news  English         NGO   
Y0007     Y0007  107835       77  90575     food  Chinese  Individual   
Y0008     Y0008  149808       15  81035     food  English  Individual   
Y0009     Y0009  189997       21  64388     food  English         NGO   

        subpervideo  viewspervideo  viewspersub  
Y0000   5428.030303    2544.939394     0.468851  
Y0001   2371.523810     313.928571     0.132374  
Y0002   2870.944444    1878.666667     0.654372  
Y0003  27367.333333    2178.000000     0.079584  
Y0004   2428.774194    1266.193548     0.521330  
Y0005    321.597826     471.489130     1.466083  
Y0006   1901.162791    1181.651163     0.621541  
Y0007   1400.454545    1176.298701     0.839941  
Y0008   9987.200000    5402.333333     0.540926  
Y0009   9047.476190    3066.095238     0.338890